"""profilr_model

Revision ID: 9fa5f7a77096
Revises: d983d041f2c2
Create Date: 2026-03-03 07:42:14.514773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa5f7a77096'
down_revision: Union[str, Sequence[str], None] = 'd983d041f2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birt_date', sa.Date(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('default_currency', sa.Enum('USD', 'EUR', 'JPY', 'CHF', 'DKK', 'UAH', 'GBP', 'AUD', 'CAD', 'CNY', 'HKD', 'NZD', 'SEK', 'NOK', 'INR', 'SGD', name='currencytype'), nullable=False),
    sa.Column('unique_key', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
