"""update_refresh_token

Revision ID: d983d041f2c2
Revises: 8f4adbb12287
Create Date: 2026-03-02 11:07:53.457175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd983d041f2c2'
down_revision: Union[str, Sequence[str], None] = '8f4adbb12287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['session_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'session_id')
    # ### end Alembic commands ###
